.TH c32lcpy 3 2022-05-11
.SH NAME
.B c32lcpy
\- safely copies a char32_t string

.SH SYNOPSIS
.B "#include <libnex/char32.h>"
.sp
.B "size_t c32lcpy (char32_t* dest, const char32_t* src, size_t size);"
.br

.SH DESCRIPTION
.B c32lcpy
copies the string specified in
.B src
to the buffer specified in
.B dest,
whose size (in char32_t's) is contained in
.B size.
.sp
.B c32lcpy
will only copy up to
.B size - 1
characters from
.B src.
It will always null terminate dest, unless
.B size
is equal to 0.
.B src
should be null terminated by the caller

.SH RETURN VALUE
.B c32lcpy
returns the length of the string it tried to create. This is the length of
.B src.
If this value is greater then or equal to the length of
.B dest,
(which is
.B size
), then the string was truncated, and this indicates an error.
The calling application must treat this an error, as otherwise, it will see
a truncated string.

.SH SEE ALSO
c32lcat(3), strlcpy(3)
